name: example
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any

dev_dependencies: 
  hottie:
    path: ../hottie
  
flutter:
  assets:
    - assets/asset.txt