name: hottie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0-dev.1

workspace:
  - example

environment:
  sdk: ^3.5.0

dependencies:
  async:
  ffi:
  test_core:
  test_api:
  vm_service:
  test:
  stack_trace:
  ansicolor:

dev_dependencies:
  very_good_analysis: ^10.0.0
