name: workspace
description: "Runs tests automatically on file changes."
publish_to: 'none'
version: 0.2.0-dev.2

workspace:
  - packages/example
  - packages/hottie

environment:
  sdk: ^3.5.0

dev_dependencies:
  very_good_analysis:
  flutter_test:
    sdk: flutter
