name: hottie
description: "Runs tests automatically on file changes."
publish_to: 'none'
version: 0.2.0-dev.2

workspace:
  - example

environment:
  sdk: ^3.5.0

dependencies:
  vm_service:
  stack_trace:
  logging:
  test_api:
  test:
  ansicolor:
  args: ^2.7.0
dev_dependencies:
  very_good_analysis: ^10.0.0

executables:
  hottie: