name: hottie
description: Experiment to run tests inside a running app, for faster feedback loop.
version: 0.0.1-dev.2

homepage: https://github.com/szotp/hottie/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test: 
    sdk: flutter
  test_api: ^0.7.7

dev_dependencies:
  lint: 
  pigeon:

flutter:
  plugin:
    platforms:
      android:
        package: com.szotp.hottie
        pluginClass: HottiePlugin
      ios:
        pluginClass: HottiePlugin
      macos:
        pluginClass: HottiePlugin