name: hottie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0-dev.1

workspace:
  - example

environment:
  sdk: ^3.5.0

dependencies:
  vm_service:
  stack_trace:
  logger:

dev_dependencies:
  very_good_analysis: ^10.0.0
