name: hottie
description: "Runs tests automatically on file changes."
publish_to: 'none'
version: 0.2.0-dev.2
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  vm_service:
  stack_trace:
  args: ^2.7.0
  test_api: any
  ffi: any
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies: 
  test: any


executables:
  hottie: